# Generated by Django 3.0.3 on 2020-03-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_getintouch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetInTouch',
            new_name='Contacts',
        ),
    ]
